### PR TITLE
Support mapping geopoint.

### PR DESCRIPTION
**Pull request by pwalsh**
# Overview

Map geopoint fields to Elasticsearch native geo_point.
---

Please preserve this line to notify @roll (lead of this repository)

### CODE REVIEW

**Review by akariv — APPROVED** [review]
LGTM

**Comment by pwalsh** [comment]
@roll any idea why the checks on this PR do not finish?

**Comment by akariv** [comment]
Seems that it still uses travis-ci.org, which had shut down a couple of months ago.
I would disconnect the requirement for it in the pull request, but I haven't got the permissions.

**Comment by roll** [comment]
Yea it needs to be migrated to Github Actions. We have migrated a lot repos to it but not these.

@akariv 
I changed your access level to admin. Can you please retry removing it? Also, might deleting travis.yaml help?

If it requires access to Travis I'll fix it on Monday.

@pwalsh 
@akariv 
In general, I think now you have all the possible access on Github but I need to check where you miss it on PyPi and add you. I will be able to do so on Monday (and a small chance today
/tomorrow)

**Comment by akariv** [comment]
(@pwalsh can you please rebase this PR to check if tests are running, completing and passing here ok?)

edit: nvm

**Comment by akariv** [comment]
https://pypi.org/project/tableschema-elasticsearch/2.1.0/

@pwalsh

**Pull request merged**
